version: 0.0
os: linux
files:
  - source: /
    destination: /app
    overwrite: true
hooks:
    ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
    Install:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
