version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - sudo npm i
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - sudo npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  base-directory: /
  files:
    - "**/*"
